### ISSUE TITLE
Error 403 Not Authorised due to Declaration of Alert::__toString() must be compatible with Genome::__toString()

### ISSUE THREAD

**Issue by desbest** [mecha-cms/x.alert#1]
### Make sure that your issue is reproducible by doing the following tasks

- [X] I am using application packages whose source code is not optimized for production (source code is not minified).
- [X] I have activated the test mode by changing the `TEST` constant value to `true` in the `.\index.php` file.
- [X] I have made sure that there are files named `error` or `error-x` or `error-y` in the `.\engine\log` folder.

### What installation method did you use?

None

### Describe your issue in the field below

Error 403 Not Authorised
Then I can't see my entire website, no matter what webpage I visit.

### Package version

Development version (package on the `main` branch)

### Package version number

3.0.0

### PHP version number

7.4.33

### What browsers are you seeing the problem on?

Others

### Error logs of the core application if any

```shell
[19-Aug-2024 11:18:24 UTC] PHP Fatal error:  Declaration of Alert::__toString() must be compatible with Genome::__toString(): string in /home/tynasite/public_html/mecha3/lot/x/alert/engine/kernel/alert.php on line 19
```

### Error log of the extension if any

```shell
N/A
```

### Error log of the layout if any

```shell
N/A
```

### General error logs if any (if the application fails to set a custom error log path, then the error log will usually appear in this location)

```shell
<br />
<b>Fatal error</b>:  Declaration of Alert::__toString() must be compatible with Genome::__toString(): string in <b>/home/tynasite/public_html/mecha3/lot/x/alert/engine/kernel/alert.php</b> on line <b>19</b><br />
```

**Comment by taufik-nurrohman** [comment]
Is this downloaded from the GitHub release page or from the website?

**Comment by desbest** [comment]
From the github release page.

**Comment by desbest** [comment]
I've tried both the version from the github release page and the `mecha-cms.com` website and I still get the same error.

**Comment by taufik-nurrohman** [comment]
Done, please re-download 👍
